export const types = {
  SET_GAME_STARTED: "SET_GAME_STARTED",
  SET_INSTRUCTIONS_EXPANDED: "SET_INSTRUCTIONS_EXPANDED",
  FETCH_DECK_RESULT: "FETCH_DECK_RESULT",
  FETCH_CARD_RESULT: "FETCH_CARD_RESULT",
  FETCH_DECK_ERROR: "FETCH_DECK_ERROR",
  FETCH_CARD_ERROR: "FETCH_CARD_ERROR",
  SET_GAME_GUESS: "SET_GAME_GUESS",
};
